version: 0.2

phases:
  install:
    runtime-versions:
        nodejs: 10
  pre_build:
    commands:
      - echo Installing Node packages
      - npm install
  build:
    commands:
      - echo Build initiated
      - npm run build
  post_build:
    commands:
      - echo Synchronizing public directory
      - aws s3 sync ./public/ s3://thexpresstrain-www-production --delete
artifacts:
  base-directory: public
  files:
    - '**/*'
  discard-paths: yes
