// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
  aws_project_region: 'ap-southeast-1',
  aws_cloud_logic_custom: [
    {
      name: 'contactForm',
      endpoint: 'https://r071i1nuxc.execute-api.ap-southeast-1.amazonaws.com/prod',
      region: 'ap-southeast-1',
    },
  ],
};

export default awsmobile;
